### ISSUE TITLE
Missing code under the LM folder

### ISSUE THREAD

**Issue by FengrunZhang** [emonosuke/emoASR#27]
Hello author, is the code not updated in time? When training the language model, 'from lm.criteria import MaskedLMLoss' did not find the relevant code.

**Comment by emonosuke** [comment]
Sorry, I added it in this commit:
https://github.com/emonosuke/emoASR/commit/b4d8d7fb3c001146bdfd85a5accec7ee592709c3 
I just forgot to `git add`.

**Comment by FengrunZhang** [comment]
Thank you!
